/*****************************************************************************/

char spicehelp_et2lst[] = 
 "Given an ephemeris epoch, compute the local solar time for an object on\n"
 "the surface of a body at a specified longitude.\n"
 "\n"
 "Brief IO:\n"
 "   (hour, min, sec, timestr, ampm) = et2lst(et, body, long, longtype)\n"
 "\n"
 "4 Arguments:\n"
 "   float - The epoch expressed in TDB seconds past the J2000 epoch at\n"
 "      which a local time is desired.\n"
 "\n"
 "   int - NAIF body ID code on which local time is to be measured\n"
 "\n"
 "   float - is the longitude (either planetocentric or planetographic)\n"
 "     in radians of the site on the surface of body for which local time\n"
 "     should be computed.\n"
 "\n"
 "   string - Form of longitude supplied, either 'PLANETOCENTRIC' or\n"
 "      ' PLANETOGRAPHIC' (case is insignificant).\n" 
 "\n"
 "4-tuple return:\n"
 "\n"
 "   int - The local \"hour\" of the site specified at the epoch 'et'. Note\n"
 "      that an \"hour\" of local time does not have the same duration as an\n"
 "      hour measured by conventional clocks.  It is simply a representation\n"
 "      of an angle.\n"
 "\n"
 "   int - The number of \"minutes\" past the hour of the local time of the\n"
 "      site at the epoch `et'. Again note that a \"local minute\" is not the\n"
 "      same as a minute you would measure with conventional clocks.\n"
 "\n"
 "   int - The number of \"seconds\" past the minute of the local time of the\n"
 "      site at the epoch `et'.  Again note that a \"local second\" is not\n"
 "      the same as a second you would measure with conventional clocks.\n"
 "\n"
 "   string - The local time on a \"24 hour\" local clock.\n"
 "\n"
 "   string - The local time on a \"12 hour\" AM/PM label clock.\n"
 "\n"
 "NOTE: See the SPICE API docs for details regarding planeographic longitude.\n"
;

/*****************************************************************************/

char spicehelp_ilumin[] = 
"Find the illumination angles (phase, solar incidence, and emission) at a\n"
"specified surface point of a target body.\n"
"\n"
"Note: See extended help for the ilumin_c function in the cspice documentation\n"
"\n"
"7 ARGUMENTS\n"
"\n"
"  string - Computation method. Currently only 'ellipsoid' is supported\n"
" (method)\n"
"\n"
"  string - Target body name (or NAIF ID)\n"
" (target)\n"
"\n"
"  float  - J2000 epoch time at which the apparent illumination angles at the\n"
"   (et)    specified surface point on the target body, as seen from the\n"
"           observing body, are to be computed.\n"
"\n"
"  string - The name of the body-fixed, body-centered reference frame \n"
" (fixref)  associated with the target body. The input surface point and the\n"
"           output vector are expressed relative to this reference frame.\n"
"\n"
"  string - Is the aberration correction to be used in computing the position\n"
" (abcorr)  and orientation of the target body and the location of the Sun.\n"
"\n"
"  string - Is the name of the observing body.  This is typically a spacecraft,\n"
" (obsrvr)  the earth, or a surface point on the earth.\n"
"\n"
"  3-tuple - Surface point on the target body, expressed in Cartesian\n"
" (spoint)  coordinates, relative to the body-fixed target frame designated by\n"
"           the 4th argument above.\n"
"\n"
"           The surface point need not be visible from the observer's \n"
"           location at the epoch time.  The components of this tuple have\n"
"           units of km.\n"
"\n"
"5 RETURNS:\n"
"\n"
"  float -  The 'surface point point epoch' defined as follows: letting 'lt'\n"
" (trgepc)  be the one-way light time between the observer and the surface\n"
"           point, this value is either the epoch 'et-lt' or 'et' depending on\n"
"           whether the requested aberration correction is for received\n"
"           radiation or omitted.  Output is in seconds past J2000 TDB.\n"
"\n"
"  3-tuple  The vector from the observers position to the surface position\n"
" (srfvec)  in the body frame provided as input.  See CSpice documentation\n"
"           for details on light time corrections.\n"
"\n"
"  float -  The angle at the surface point between the observer-surface line\n"
" (phase)   and the sun-surfac line.  Output is in radians from 0 to PI.\n"
"\n"
"  float -  The angle between the surface normal vector and the surface\n"
" (solar)   point - sun line.  Output is in radians from 0 to PI.\n"
"\n"
"  float -  The angle between the surface normal vector and the surface\n" 
" (emissn)  point - observer line. Output is in radians from 0 to PI.\n"
"\n";

/*****************************************************************************/

char spicehelp_subpnt[] = 
"Compute the rectangular coordinates of the sub-observer point on a target\n"
"body at a specified epoch, optionally corrected for light time and stellar\n"
"aberration.\n"
"\n"
"6 Arguments:\n"
"\n"
"  1 Method -- is a short string providing parameters defining the computation\n"
"      method to be used.  The supported values of 'method' are listed below.\n"
"      Please note that the colon is a required delimiter; using a blank will\n"
"      not work.\n"
"\n"
"        'Near point: ellipsoid'  The sub-observer point computation uses a\n" 
"                                 triaxial ellipsoid to model the surface of\n"
"                                 the target body. The sub-observer point is\n" 
"                                 defined as the nearest point on the target\n"
"                                 relative to the observer.\n"
"\n" 
"        'Intercept: ellipsoid'   The sub-observer point computation uses a\n" 
"                                 triaxial ellipsoid to model the surface of\n"
"                                 the target body. The sub-observer point is\n"
"                                 defined as the target surface intercept of\n"
"                                 the line containing the observer and the\n"
"                                 target's center.\n"
"\n"
"      Neither case nor white space are significant in 'method'. For example,\n"
"      the string  ' nearpoint:ELLIPSOID ' is valid.\n"
"\n"
"  2 Target -- is the name of the target body. The target body is an \n"
"      ephemeris object (its trajectory is given by SPK data), and is an\n"
"      extended object.\n"
"\n"
"      The string 'target' is case-insensitive, and leading and trailing\n"
"      blanks in 'target' are not significant. Optionally, you may supply a\n"
"      string containing the integer ID code for the object. For example both\n" 
"      'MOON' and '301' are legitimate strings that indicate the Moon is the\n"
"      target body.\n"
"\n"
"      When the target body's surface is represented by a tri-axial ellipsoid,\n"
"      this routine assumes that a kernel variable representing the \n"
"      ellipsoid's radii is present in the kernel pool. Normally the kernel\n"
"      variable would be defined by loading a PCK file.\n"
"\n"
"  3 ET --  is the epoch of participation of the observer, expressed as\n"
"      ephemeris seconds past J2000 TDB: 'ET' is the epoch at which the\n"
"      observer's state is computed. \n"
"\n"
"      When aberration corrections are not used, 'ET' is also the epoch at\n"
"      which the position and orientation of the target body are computed.\n"
"\n" 
"      When aberration corrections are used, the position and orientation of\n"
"      the target body are computed at et-lt or et+lt, where 'lt' is the \n"
"      one-way light time between the sub-observer point and the observer,\n"
"      and the sign applied to 'lt' depends on the selected correction. See\n"
"      the description of 'abcorr' below for details.\n"
"\n" 
"  4 fixref -- is the name of the body-fixed, body-centered reference frame\n"
"      associated with the target body. The output sub-observer point 'spoint'\n"
"      will be expressed relative to this reference frame. The string 'fixref'\n"
"      is case-insensitive, and leading and trailing blanks in 'fixref' are\n"
"      not significant.\n"
"\n"
"  5 abcorr -- indicates the aberration corrections to be applied when \n"
"      computing the target's position and orientation.  For remote sensing\n"
"      applications, where the apparent sub-observer point seen by the\n"
"      observer is desired, normally either of the corrections:\n"
"\n"
"        'LT+S'\n"  
"        'CN+S'\n"
"\n"
"      should be used. These and the other supported options are described\n"
"      below. 'abcorr' may be any of the following:\n"
"\n" 
"        'NONE' Apply no correction. Return the geometric sub-observer point\n"
"               on the target body.\n"
"\n"
"      Let 'lt' represent the one-way light time between the observer and the\n"
"      sub-observer point (note: NOT between the observer and the target\n"
"      body's center).\n"
"\n"
"      The following values of 'abcorr' apply to the 'reception' case in which\n"
"      photons depart from the sub-observer point's location at the light-time\n"
"      corrected epoch et-lt and *arrive* at the observer's location at 'et':\n"
"\n"
"        'LT'   Correct for one-way light time (also called 'planetary \n"
"               aberration') using a Newtonian formulation. This correction\n"
"               yields the location of sub-observer point at the moment it\n"
"               emitted photons arriving at the observer at 'et'.\n"
"\n"        
"               The light time correction uses an iterative solution of the\n"
"               light time equation. The solution invoked by the 'LT' option\n"
"               uses one iteration.\n"
"\n"            
"               Both the target position as seen by the observer, and rotation\n"
"               of the target  body, are corrected for light time.\n"
"\n"
"        'LT+S' Correct for one-way light time and stellar aberration using a\n"
"               Newtonian formulation.  This option modifies the sub-observer\n"
"               point obtained with the 'LT' option to account for the\n"
"               observer's velocity relative to the solar system barycenter.\n"
"               These corrections yield the apparent sub-observer point.\n"
"\n"
"        'CN'   Converged Newtonian light time correction. In solving the\n"
"               light time equation, the 'CN' correction iterates until the\n"
"               solution converges. Both the position and rotation of the\n"
"               target body are corrected for light time.\n"
"\n" 
"        'CN+S' Converged Newtonian light time and stellar aberration\n"
"               corrections. This option produces a solution that is at least\n"
"               as accurate at that obtainable with the 'LT+S' option. Whether\n"
"               the 'CN+S' solution is substantially more accurate depends on\n"
"               the geometry of the participating objects and on the accuracy\n"
"               of the input data. In all cases this routine will execute more\n" 
"               slowly when a converged solution is computed.\n"
"\n"
"      The following values of 'abcorr' apply to the 'transmission' case in\n"
"      which photons *depart* from the observer's location at 'et' and arrive\n"
"      at the sub-observer point at the light-time corrected epoch et+lt:\n"
"\n"
"        'XLT'   'Transmission' case: correct for one-way light time using a\n"
"                Newtonian formulation. This correction yields the sub-\n"
"                observer location at the moment it receives photons emitted\n"
"                from the observer's location at 'et'.\n"
"\n"
"                The light time correction uses an iterative solution of the\n"
"                light time equation. The solution invoked by the 'LT' option\n"
"                uses one iteration.\n"
"\n" 
"                Both the target position as seen by the observer, and \n"
"                rotation of the target body, are corrected for light time.\n"
"\n" 
"        'XLT+S' 'Transmission' case: correct for one-way light time and\n"
"                stellar aberration using a Newtonian formulation  This option\n"
"                modifies the sub-observer point obtained with the 'XLT'\n"
"                option to account for the observer's velocity relative to the\n"
"                solar system barycenter.\n"
"\n" 
"        'XCN'   Converged Newtonian light time correction. This is the same\n"
"                as 'XLT' correction but with further iterations to a\n"
"                converged Newtonian light time solution.\n"
"\n"
"        'XCN+S' 'Transmission' case: converged Newtonian light time and\n"
"                stellar aberration corrections.\n"
"\n"
"    Neither case nor white space are significant in 'abcorr'. For example,\n"
"    the string: 'Lt + s' is valid.\n"
"\n"
"  6 obsrvr -- is the name of the observing body. The observing body is an\n"
"      ephemeris object: it typically is a spacecraft, the earth, or a surface\n"
"      point on the earth. 'obsrvr' is case-insensitive, and leading and\n"
"      trailing blanks in 'obsrvr' are not significant. Optionally, you may\n"
"      supply a string containing the integer ID code for the object. For\n"
"      example both 'MOON' and '301' are legitimate strings that indicate the\n"
"      Moon is the observer.\n"
"\n"
"3 Return Values\n"
"\n"
"  1 spoint -- 3-tuple of the sub-observer point on the target body.\n"
"\n"
"      The sub-observer point is defined either as the point on the target\n"
"      body that is closest to the observer, or the target surface intercept\n"
"      of the line from the observer to the target's center; the input\n"
"      argument 'method' selects the definition to be used.\n"
"\n"
"      'spoint' is expressed in Cartesian coordinates, relative to the body-\n"
"      fixed target frame designated by 'fixref'. The body-fixed target frame\n"
"      is evaluated at the sub-observer epoch 'trgepc' (see description below).\n"
"\n"
"      When light time correction is used, the duration of light travel between\n"
"      'spoint' to the observer is considered to be the one way light time.\n"
"\n"
"      When aberration corrections are used, 'spoint' is computed using target\n"
"      body position and orientation that have been adjusted for the\n"
"      corrections applicable to 'spoint' itself rather than to the target\n"
"      body's center. In particular, if the stellar aberration correction\n"
"      applicable to 'spoint' is represented by a shift vector 's', then the\n"
"      light-time corrected position of the target is shifted by 's' before the\n"
"      sub-observer point is computed.\n"
"\n"                
"      The components of 'spoint' have units of km.\n"
"\n"
"  2 trgepc -- is the 'sub-observer point epoch.' 'trgepc' is defined as follows:\n"
"\n"
"      letting 'lt' be the one-way light time between the observer and the\n"
"      sub-observer point, 'trgepc' is the epoch et-lt, et+lt, or 'et' depending\n"
"      on whether the requested aberration correction is, respectively, for\n"
"      received radiation, transmitted radiation, or omitted. 'lt' is computed\n"
"      using the method indicated by 'abcorr'.\n"
"\n"
"      'trgepc' is expressed as seconds past J2000 TDB.\n"
"\n"
"  3 srfvec -- is a 3-tuple of the vector from the observer's position at 'et'\n"
"      to the aberration-corrected (or optionally, geometric) position of \n"
"      'spoint', where the aberration corrections are specified by 'abcorr'.\n"
"      'srfvec' is expressed in the target body-fixed reference frame\n"
"      designated by 'fixref', evaluated at 'trgepc'.\n"
"\n"
"      The components of 'srfvec' are given in units of km.\n"
"\n" 
"      One can use the CSPICE function vnorm_c to obtain the distance between\n"
"      the observer and 'spoint':\n" 
"\n" 
"         dist = vnorm( srfvec )\n"
"\n"       
"      The observer's position 'obspos', relative to the target body's center,\n"
"      where the center's position is corrected for aberration effects as\n"
"      indicated by 'abcorr', can be computed via the call:\n" 
"\n" 
"      vsub( spoint, srfvec, obspos )\n"
"\n" 
"      To transform the vector 'srfvec' to a time-dependent reference frame \n"
"      'ref' at 'et', a sequence of two frame transformations is required. For\n"
"      example, let 'mfix' and 'mref' be 3x3 matrices respectively describing\n"
"      the target body-fixed to J2000 frame transformation at 'trgepc' and the\n"
"      J2000 to (time-dependent frame) 'ref' transformation at 'et', and let\n"
"      'xform' be the 3x3 matrix representing the composition of 'mref' with\n"
"      'mfix'. Then 'srfvec' can be transformed to the result 'refvec' as\n"
"      follows:\n"
"\n" 
"         pxform( fixref,  'j2000', trgepc, mfix  )\n"
"         pxform( 'j2000', ref,     et,     mref  )\n"
"         mxm   ( mref,    mfix,            xform )\n"
"         mxv   ( xform,   srfvec,          refvec )\n"
"\n" 
"      The second example in the Examples header section below presents a\n"
"      complete program that demonstrates this procedure.\n"
"\n";

/*****************************************************************************/
/* Sub-solar point */

char spicehelp_subslr[] = 
"Compute the rectangular coordinates of the sub-solar point on a target body\n"
"at a specified epoch, optionally corrected for light time and stellar\n"
"aberration.\n"
"\n"
"NOTE: This funciton is exactly the same as subpnt, only instead of\n"
"      calculating the sub-observer-point the sub-solar-point is calculatied by\n"
"      spice instead.  See detailed notes in the C API docs.\n"
"\n"
"6 ARUGMENTS\n"
"  method (string)  Computation method\n"
"  target (string)  Name of target body\n"
"  et     (float)   Epoch in ephemeris seconds past J2000 TDB\n"
"  fixref (string)  Body-fixed, body-centered target body frame\n"
"  abcorr (string)  Aberration correction\n"
"  obsrvr (string)  Name of observing body\n"
"\n"
"3 RETURNS\n"
"   spoint (3-tuple, floats)  Sub-solar point on the target body. \n"
"   trgepc (float)  Sub-solar point epoch. \n"
"   srfvec (3-tuple, floats)  Vector from observer to sub-solar point.\n"
"\n";
